version: "3.9"
services:
  db:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: aihf
      POSTGRES_PASSWORD: aihf
      POSTGRES_DB: aihf
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aihf -d aihf"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    ports: ["6379:6379"]
    volumes:
      - redis_data:/data

  adminer:
    image: adminer
    ports: ["8080:8080"]
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  db_data:
  redis_data: